cc_library(
    name = "comm",
    srcs = [
        "comm.cpp",
    ],
    hdrs = [
        "comm.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//comm/error",
        "//comm/log",
    ],
)
