cc_library(
    name = "core",
    srcs = [
        "core.cpp",
    ],
    hdrs = [
        "core.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//lib/error",
        "//lib/log",
    ],
)
