cc_library(
    name = "net",
    srcs = [
        "inet_address.cpp",
        "socket.cpp",
    ],
    hdrs = [
        "inet_address.h",
        "socket.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//lib/log",
    ],
)
